name       : retro-gtk
version    : 0.12.1
release    : 4
source     :
    - https://download.gnome.org/sources/retro-gtk/0.12/retro-gtk-0.12.1.tar.xz : daadab43c8189d92be5832e2cfbf1afdfa6ad3201933cc946a2d6761bfd5b166
license    : GPL-3.0
component  : programming.library
summary    : retro-gtk is a toolkit to write  GTK+ 3 based Libretro frontends.
description: |
    retro-gtk is a toolkit to write  GTK+ 3 based Libretro frontends.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpulse)
    - vala
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
